apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmitm-mobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmitm-mobile
  template:
    metadata:
      labels:
        app: mmitm-mobile
    spec:
      containers:
        - name: mmitm-mobile
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
